# SPDX-License-Identifier: LGPL-2.1-or-later
# mica — the configuration language: predicates, the option graph and its
# resolution. One compilation unit (`libmica.rlib`) used by the buildutil
# engine, which resolves configuration in process, and by the `buildutil
# config` commands, the person-facing configuration front end.

[derivation.lib-mica]
builder = "rustc-crate"
tool = "rustc"
host-tool = true
allowed-references = "closure"
src-dirs = ["tools/buildutil/lib/mica"]
outputs = ["libmica.rlib"]
argv = [
  "--edition=2024",
  "-O",
  "--crate-type=lib",
  "--crate-name=mica",
  "-o", "{out}/libmica.rlib",
  "{srcroot}/tools/buildutil/lib/mica/lib.rs",
]

[derivation.lib-mica-bootstrap]
builder = "rustc-crate"
tool = "rustc"
bootstrap = true
host-tool = true
src-dirs = ["tools/buildutil/lib/mica"]
outputs = ["libmica.rlib"]
argv = [
  "--edition=2024",
  "-O",
  "--crate-type=lib",
  "--crate-name=mica",
  "-o", "{out}/libmica.rlib",
  "{srcroot}/tools/buildutil/lib/mica/lib.rs",
]
