// SPDX-License-Identifier: LGPL-2.1-or-later
//! mica — deterministic artifact emitters
//!
//! Six artifacts, all sorted by option name, no timestamps, written
//! atomically and only when the content changed (stable mtimes keep
//! downstream regeneration quiet):
//!   config.keyval       — KEY=VALUE for meson (plus cfg aggregates)
//!   config.rs           — Rust constants
//!   config.h            — C defines
//!   kernel.cfgs         — one rustc --cfg name per line (kernel scope)
//!   userland.cfgs       — one rustc --cfg name per line (userland scope)
//!   features.manifest   — the config-identity artifact (buildutil hashes it)

use crate::config::graph::{Graph, Scope, Type};
use crate::config::resolve::Resolved;
use crate::config::toml::Value;
use std::io;
use std::path::Path;

/// rustc `--cfg` names for one scope: `rust_cfg` names of on-bools plus
/// `rust_cfg_each_prefix`-expanded comma-list items; sorted, deduplicated.
pub fn cfgs_for(graph: &Graph, resolved: &Resolved, scope: Scope) -> Vec<String> {
    let mut out = Vec::new();
    for (name, def) in &graph.options {
        if def.scope != scope {
            continue;
        }
        let r = &resolved.values[name];
        if let Some(cfg) = &def.rust_cfg {
            if r.value == Value::Bool(true) {
                out.push(cfg.clone());
            }
        }
        if let Some(prefix) = &def.rust_cfg_each_prefix {
            if let Value::Str(list) = &r.value {
                for item in list.split(',') {
                    let item = item.trim();
                    if !item.is_empty() {
                        out.push(format!("{}{}", prefix, item));
                    }
                }
            }
        }
    }
    out.sort();
    out.dedup();
    out
}

fn keyval_value(value: &Value) -> String {
    match value {
        Value::Bool(b) => b.to_string(),
        Value::Int(n) => n.to_string(),
        Value::Str(s) => s.clone(),
        Value::Array(items) => items.join(","),
        Value::IntList(items) => crate::config::resolve::join_ints(items),
    }
}

fn active_label(graph: &Graph, resolved: &Resolved, choice: &str) -> String {
    resolved.choices[choice]
        .active
        .as_ref()
        .and_then(|m| graph.options[m].value_label.clone())
        .unwrap_or_default()
}

/// The resolved `KEY=VALUE` table, sorted by key: every non-computed
/// option, each choice's active member value, and the two rustc cfg
/// aggregates. The engine reads these rows in process; `config.keyval` is their
/// text form.
pub fn keyval_rows(graph: &Graph, resolved: &Resolved) -> Vec<(String, String)> {
    let mut rows: Vec<(String, String)> = Vec::new();
    for (name, def) in &graph.options {
        if def.computed || def.ty == Type::ChoiceMember {
            continue;
        }
        rows.push((name.clone(), keyval_value(&resolved.values[name].value)));
    }
    for name in graph.choices.keys() {
        rows.push((Graph::choice_key(name), active_label(graph, resolved, name)));
    }
    rows.push((
        "KERNEL_RUST_CFGS".to_string(),
        cfgs_for(graph, resolved, Scope::Kernel).join(","),
    ));
    rows.push((
        "USERLAND_RUST_CFGS".to_string(),
        cfgs_for(graph, resolved, Scope::Userland).join(","),
    ));
    rows.sort();
    rows
}

fn render_keyval(graph: &Graph, resolved: &Resolved) -> String {
    let mut out = String::new();
    for (k, v) in keyval_rows(graph, resolved) {
        out.push_str(&k);
        out.push('=');
        out.push_str(&v);
        out.push('\n');
    }
    out
}

fn render_config_rs(graph: &Graph, resolved: &Resolved) -> String {
    let mut out = String::from("// Generated by buildutil config. Do not edit.\n");
    let mut rows: Vec<(String, String)> = Vec::new();
    for (name, def) in &graph.options {
        let r = &resolved.values[name];
        let line = match &r.value {
            Value::Bool(b) => format!("pub const {}: bool = {};", name, b),
            Value::Int(n) => {
                if def.min.unwrap_or(0) >= 0 && *n >= 0 {
                    format!("pub const {}: usize = {};", name, n)
                } else {
                    format!("pub const {}: i64 = {};", name, n)
                }
            }
            Value::Str(s) => format!("pub const {}: &str = {:?};", name, s),
            Value::IntList(items) => {
                let element = if def.min.unwrap_or(0) >= 0 && items.iter().all(|n| *n >= 0) {
                    "usize"
                } else {
                    "i64"
                };
                let body = items
                    .iter()
                    .map(|n| n.to_string())
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("pub const {}: &[{}] = &[{}];", name, element, body)
            }
            Value::Array(_) => unreachable!("options never resolve to string arrays"),
        };
        rows.push((name.clone(), line));
    }
    for name in graph.choices.keys() {
        let key = Graph::choice_key(name);
        let label = active_label(graph, resolved, name);
        rows.push((
            key.clone(),
            format!("pub const {}: &str = {:?};", key, label),
        ));
    }
    rows.sort();
    for (_, line) in rows {
        out.push_str(&line);
        out.push('\n');
    }
    out
}

fn render_config_h(graph: &Graph, resolved: &Resolved) -> String {
    let mut out = String::from(
        "/* Generated by buildutil config. Do not edit. */\n#ifndef SALTYOS_CONFIG_H\n#define SALTYOS_CONFIG_H\n",
    );
    let mut rows: Vec<(String, String)> = Vec::new();
    for (name, _def) in &graph.options {
        let r = &resolved.values[name];
        let line = match &r.value {
            Value::Bool(true) => format!("#define CONFIG_{} 1", name),
            Value::Bool(false) => format!("/* CONFIG_{} is not set */", name),
            Value::Int(n) => format!("#define CONFIG_{} {}", name, n),
            Value::Str(s) => format!("#define CONFIG_{} {:?}", name, s),
            Value::IntList(items) => format!(
                "#define CONFIG_{} {:?}",
                name,
                crate::config::resolve::join_ints(items)
            ),
            Value::Array(_) => unreachable!("options never resolve to string arrays"),
        };
        rows.push((name.clone(), line));
    }
    for name in graph.choices.keys() {
        let key = Graph::choice_key(name);
        let label = active_label(graph, resolved, name);
        rows.push((key.clone(), format!("#define CONFIG_{} {:?}", key, label)));
    }
    rows.sort();
    for (_, line) in rows {
        out.push_str(&line);
        out.push('\n');
    }
    out.push_str("#endif\n");
    out
}

fn render_cfgs(names: &[String]) -> String {
    let mut out = String::new();
    for name in names {
        out.push_str(name);
        out.push('\n');
    }
    out
}

fn render_manifest(graph: &Graph, resolved: &Resolved) -> String {
    let mut out = String::from("# buildutil config feature manifest\n");
    for (name, state) in &resolved.choices {
        out.push_str(&format!(
            "choice {} active={} visible={}\n",
            name,
            state.active.as_deref().unwrap_or("-"),
            if state.visible { "yes" } else { "no" }
        ));
    }
    for (name, def) in &graph.options {
        let r = &resolved.values[name];
        out.push_str(&format!(
            "option {} type={} value={} origin={} visible={}\n",
            name,
            def.ty.name(),
            keyval_value(&r.value),
            r.origin.as_str(),
            if r.visible { "yes" } else { "no" }
        ));
    }
    out
}

/// Write `content` to `dir/name` only if it differs; atomic temp + rename.
/// Returns true when the file changed.
fn write_if_changed(dir: &Path, name: &str, content: &str) -> io::Result<bool> {
    let path = dir.join(name);
    if let Ok(existing) = std::fs::read_to_string(&path) {
        if existing == content {
            return Ok(false);
        }
    }
    let tmp = dir.join(format!(".{}.tmp", name));
    std::fs::write(&tmp, content)?;
    std::fs::rename(&tmp, &path)?;
    Ok(true)
}

/// Emit all six artifacts into `out_dir`; returns true if anything changed.
pub fn emit_all(graph: &Graph, resolved: &Resolved, out_dir: &Path) -> io::Result<bool> {
    std::fs::create_dir_all(out_dir)?;
    let kernel_cfgs = cfgs_for(graph, resolved, Scope::Kernel);
    let userland_cfgs = cfgs_for(graph, resolved, Scope::Userland);
    let mut changed = false;
    changed |= write_if_changed(out_dir, "config.keyval", &render_keyval(graph, resolved))?;
    changed |= write_if_changed(out_dir, "config.rs", &render_config_rs(graph, resolved))?;
    changed |= write_if_changed(out_dir, "config.h", &render_config_h(graph, resolved))?;
    changed |= write_if_changed(out_dir, "kernel.cfgs", &render_cfgs(&kernel_cfgs))?;
    changed |= write_if_changed(out_dir, "userland.cfgs", &render_cfgs(&userland_cfgs))?;
    changed |= write_if_changed(
        out_dir,
        "features.manifest",
        &render_manifest(graph, resolved),
    )?;
    Ok(changed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::resolve::{self, Overrides};
    use crate::config::{graph, toml};
    use std::path::{Path, PathBuf};

    const SRC: &str = r#"
[option.DEBUG_SERIAL]
type = "bool"
default = true

[option.NO_SERIAL_OUTPUT]
type = "bool"
computed = true
default = "true if !DEBUG_SERIAL else false"
rust_cfg = "no_serial_output"
scope = "kernel"

[option.KERNEL_DEBUG_MODULES]
type = "string"
default = "mm, ipc"
rust_cfg_each_prefix = "klog_mod_"
scope = "kernel"

[option.KLOG_WARN]
type = "bool"
computed = true
default = true
rust_cfg = "klog_warn"
scope = "kernel"

[option.ULOG_WARN]
type = "bool"
computed = true
default = true
rust_cfg = "ulog_warn"
scope = "userland"

[option.KERNEL_STACK_SIZE]
type = "int"
default = 16384
min = 4096
max = 65536

[choice.arch]
default = "ARCH_X86_64"
  [choice.arch.option.ARCH_X86_64]
  [choice.arch.option.ARCH_AARCH64]
"#;

    fn build() -> (graph::Graph, resolve::Resolved) {
        let doc = toml::parse(Path::new("g.toml"), SRC).unwrap();
        let g = graph::from_docs(&[doc]).unwrap();
        assert!(graph::validate(&g).is_empty());
        let r = resolve::resolve(&g, &Overrides::default()).unwrap();
        (g, r)
    }

    fn tmpdir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("buildutil-config-emit-{}-{}", tag, std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn cfg_lists_sorted_and_expanded() {
        let (g, r) = build();
        let cfgs = cfgs_for(&g, &r, Scope::Kernel);
        assert_eq!(cfgs, vec!["klog_mod_ipc", "klog_mod_mm", "klog_warn"]);
        assert_eq!(cfgs_for(&g, &r, Scope::Userland), vec!["ulog_warn"]);
    }

    #[test]
    fn keyval_shape() {
        let (g, r) = build();
        let kv = render_keyval(&g, &r);
        assert!(kv.contains("ARCH=x86_64\n"));
        assert!(kv.contains("KERNEL_STACK_SIZE=16384\n"));
        assert!(kv.contains("KERNEL_RUST_CFGS=klog_mod_ipc,klog_mod_mm,klog_warn\n"));
        assert!(kv.contains("USERLAND_RUST_CFGS=ulog_warn\n"));
        // Computed options and members stay out of the keyval surface.
        assert!(!kv.contains("NO_SERIAL_OUTPUT"));
        assert!(!kv.contains("ARCH_X86_64="));
        // Sorted by key.
        let keys: Vec<&str> = kv.lines().map(|l| l.split('=').next().unwrap()).collect();
        let mut sorted = keys.clone();
        sorted.sort();
        assert_eq!(keys, sorted);
    }

    #[test]
    fn rust_and_c_headers() {
        let (g, r) = build();
        let rs = render_config_rs(&g, &r);
        assert!(rs.contains("pub const KERNEL_STACK_SIZE: usize = 16384;"));
        assert!(rs.contains("pub const ARCH: &str = \"x86_64\";"));
        assert!(rs.contains("pub const ARCH_AARCH64: bool = false;"));
        let h = render_config_h(&g, &r);
        assert!(h.contains("#define CONFIG_KERNEL_STACK_SIZE 16384"));
        assert!(h.contains("/* CONFIG_ARCH_AARCH64 is not set */"));
        assert!(h.contains("#define CONFIG_ARCH \"x86_64\""));
    }

    #[test]
    fn emit_is_idempotent() {
        let (g, r) = build();
        let dir = tmpdir("idem");
        assert!(emit_all(&g, &r, &dir).unwrap());
        assert!(!emit_all(&g, &r, &dir).unwrap());
        let manifest = std::fs::read_to_string(dir.join("features.manifest")).unwrap();
        assert!(manifest.contains("choice arch active=ARCH_X86_64 visible=yes"));
        assert!(
            manifest.contains(
                "option NO_SERIAL_OUTPUT type=bool value=false origin=default visible=yes"
            )
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
